# NDR Platform v2.1.0 Funding Configuration
# Support the development of the production-ready NDR Platform
# These are supported funding model platforms

# GitHub Sponsors
github: Shizukaax

# Custom funding options
custom: ["mailto:justinchua@tunglok.com"]

# Uncomment and add if you set up other funding platforms:
# patreon: your-patreon-username
# open_collective: your-opencollective-name  
# ko_fi: your-kofi-username
# tidelift: "npm/package-name"
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
