blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation  
    url: https://github.com/Shizukaax/ndr-platform/tree/main/guides
    about: Check our comprehensive guides documentation before reporting issues
  - name: 💬 GitHub Discussions
    url: https://github.com/Shizukaax/ndr-platform/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: mailto:justinchua@tunglok.com
    about: Report security vulnerabilities privately via email (see SECURITY.md)
  - name: 🆘 Get Support
    url: https://github.com/Shizukaax/ndr-platform/blob/main/.github/SUPPORT.md
    about: Learn how to get help with NDR Platform v2.1.0
