anomaly_detection:
  default_threshold: 0.8
  max_anomalies: 1000
  models:
    isolation_forest:
      enabled: true
      contamination: 0.05
      n_estimators: 100
      max_samples: "auto"
      random_state: 42
    local_outlier_factor:
      enabled: true
      n_neighbors: 20
      contamination: 0.05
      algorithm: "auto"
    one_class_svm:
      enabled: true
      nu: 0.05
      kernel: "rbf"
      gamma: "scale"
    dbscan:
      enabled: true
      eps: 0.5
      min_samples: 5
      algorithm: "auto"
    knn:
      enabled: true
      n_neighbors: 5
      algorithm: "auto"
      metric: "minkowski"
    hdbscan:
      enabled: false
      min_cluster_size: 5
      min_samples: null
      alpha: 1.0
    ensemble:
      enabled: true
      combination_method: "weighted_average"

visualization:
  color_theme: "blue"
  max_points_scatter: 5000
  max_nodes_network: 100
  default_chart_height: 400

reports:
  output_dir: "data/reports"
  include_charts: true
  include_raw_data: false
  default_format: "html"

mitre:
  techniques_file: "config/mitre_attack_data.json"
  confidence_threshold: 0.6

feedback:
  storage_dir: "data/feedback"
  use_feedback_for_training: true

system:
  cache_dir: "cache"
  models_dir: "models"
  data_dir: "data"
  json_data_dir: "data/json"
  reports_dir: "data/reports"
  results_dir: "data/results"
  log_level: "INFO"

# Anomaly History Storage (Persistent Data)
anomaly_storage:
  history_dir: "data/anomaly_history"
  max_retention_days: 90  # Keep anomaly history for 90 days
  backup_enabled: true
  backup_interval_hours: 24
  compression_enabled: false

# Single Data Source Configuration
# For development: "C:\\Users\\justinchua\\Desktop\\newnewapp\\data\\json"
# For production: "/opt/arkime/json"
data_source:
  directory: "./data/json/"
  file_pattern: "*.json"
  max_files: 100
  recursive: true
  # Note: polling_interval is legacy - we now use monitoring.real_time.auto_refresh_interval
  polling_interval: 1  # seconds for real-time monitoring (deprecated)
  auto_refresh: true

# Monitoring and Alert Settings
monitoring:
  alerts:
    default_threshold: 0.7
    high_risk_threshold: 0.8
    notification_delay: 5  # seconds between notifications
  performance:
    max_historical_points: 100
    metrics_update_interval: 5  # seconds
    max_buffer_size: 1000
    retention_hours: 24
  real_time:
    # Auto-refresh configuration (primary monitoring method)
    auto_refresh_interval: 300  # seconds (5 minutes = 300 seconds)
    enable_auto_refresh: true
    file_change_notifications: true
    # Anomaly detection configuration
    anomaly_detection:
      enabled: true
      model_type: "ensemble"  # Options: "isolation_forest", "local_outlier_factor", "one_class_svm", "knn", "ensemble"
      ensemble_config:
        method: "weighted_average"  # Options: "average", "maximum", "weighted_average"
        models:
          isolation_forest:
            enabled: true
            weight: 0.4
            contamination: 0.05
          local_outlier_factor:
            enabled: true
            weight: 0.3
            contamination: 0.05
          one_class_svm:
            enabled: true
            weight: 0.3
            contamination: 0.05
          knn:
            enabled: false
            weight: 0.0
            contamination: 0.05
      single_model_fallback: "isolation_forest"  # Fallback if ensemble fails
      confidence_threshold: 0.7  # Minimum confidence for alerts